### PR TITLE
Update from Phore v1.3.3.1

### PR DESCRIPTION
**Pull request by wqking**

### CODE REVIEW

**Comment by 2a5A1Ghu1** [comment]
Does not compile on macOS 10.15 using

`./autogen.sh && ./configure LDFLAGS="-L/usr/local/opt/openssl/lib" CPPFLAGS="-I/usr/local/opt/openssl/include" PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig" --disable-tests --with-unsupported-ssl && make && make deploy`

Screen Shot 2021-04-16 at 10 27 17 PM

Manually creating temp_send_locale.qrc from send_locale.qrc allows it to compile and make deploy works.
Screen Shot 2021-04-16 at 10 33 36 PM

**Comment by wqking** [comment]
Can you make clean and try again? I don't have Mac and I can't reproduce it on Linux.

**Comment by 2a5A1Ghu1** [comment]
> Can you make clean and try again? I don't have Mac and I can't reproduce it on Linux.

With or without the file I created?

Edit:
I did it without the file I made and it failed to build after a make clean...
Screen Shot 2021-04-18 at 12 24 25 AM

Note: make clean deletes the file I made...

edit:
Running make clean with the file and then building results in a completed build. Very weird

**Comment by wqking** [comment]
I merged your PR #2, I'm not sure if it helps.

**Comment by 2a5A1Ghu1** [comment]
> I merged your PR #2, I'm not sure if it helps.

That file only is ran during "make deploy" the error occurs before that part of the build process.

**Pull request merged**
