### PR TITLE
Update from Phore upstream v1.2.2

### PR DESCRIPTION
**Pull request by wqking**
When merging it, be sure to keep the commit history, don't squash the PR into a single commit.

This update has some problems that we need to investigate.
When running this update on mainnet, it reports error "incorrect proof of work (DGW pre-fork)" at block 37 and the sync can't continue. The PoW related code was not changed in this update.
When I tried the send-qt downloaded from the official site, send-qt doesn't sync at all and report error "Check your wallet version, there is a new protocol on the network.".
We need to make send-qt works, then see if it has issues on block 37.
I build the master and do a test, the sync gets stuck at block 37 for PoW verification error, same as the one in the PR.

### CODE REVIEW

**Comment by squidicuzz** [comment]
*Moved From: https://github.com/SocialSend/SocialSend/pull/27*

----
> I build the master and do a test, the sync gets stuck at block 37 for PoW verification error, same as the one in the PR.

I have the same issue.  It was a missed problem between version `1.2.1.0` and `1.2.1.5`. I am not sure exactly what the change or issue is yet..  Version `1.2.1.0` should not have this issue and is able to sync.

The warning about protocol version is just an alert message about a protocol version change, and should not effect anything.

> When I tried the send-qt downloaded from the official site, send-qt doesn't sync at all and report error "Check your wallet version, there is a new protocol on the network.".

Please try adding some nodes manually.  I am not sure if the seed nodes listed in the older version are still online.  Ignore the protocol version warning..

Try these nodes to get synced up:
- `fr.socialsend.io`
- `de.socialsend.io`
- `us-e1.socialsend.io`
- `us-e2.socialsend.io`

**Comment by 2a5A1Ghu1** [comment]
I will compile as well and check on macOS versions 10.15/11 intel and macOS 11 arm(M1)

As @squidicuzz has said there was a change in a previous version that caused a sync issue that was missed. There where only some minor updates so hopefully we can find it easily.

**Comment by 2a5A1Ghu1** [comment]
Will not compile on macOS 10.15+
brew no longer supports openssl 1.0.*, bitcoin upstream has dropped openssl completely and PIVX upstream has moved to  1.1*. Seeing how we will not be adding zerocoin, moving to pivx's and then bitcoins solution should be pretty safe in the near future.

Attempting to compile depends to use depends libs instead of brew installed libs resulted in failed downloads.
`
Fetching v1.1.0.tar.bz2 from https://bitbucket.org/al45tair/ds_store/get
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Fetching v1.1.0.tar.bz2 from https://bitcoincore.org/depends-sources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
`

Apple and brew no longer support any os versions below 10.14 and will result in ssl cert errors when trying to download prerequisite libs. Depends should probably reflect this. Machines that can not update to at least 10.15 are over 10 years old. The general EOL for apple device service parts is 7 years.

This is great to because the separate dmgs for multiple version of mac os x can be dropped if depends and gittian can be updated building for 10.14 and higher using the 10.15.1 SDK (xcode version 11.3.1)

I know this is just the start of getting matched up with upstream, just noting the issues here for later, I will try to build on an older version of Mac OS X shortly...

**Comment by 2a5A1Ghu1** [comment]
I made a pr to fix the make deploy issue for macOS (10.15 is what I tested the fix on) 

https://github.com/wqking-misc/SocialSend/pull/1

if I did the pr on the wrong branch please let me know I will redo it. @wqking

**Pull request merged**
